language: bash

jdk:
  - oraclejdk13

services:
  - docker

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew currentVersion
  - ./gradlew docker
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker tag ping-pong-game:"$(./gradlew currentVersion)" smeetshah/ping-pong-game:latest
  - docker push smeetshah/ping-pong-game:latest

