language: bash

jdk:
  - oraclejdk13

services:
  - docker

os: osx

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build
  - docker build -t ping-pong-game .
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker tag ping-pong-game smeetshah/ping-pong-game:latest
  - docker push smeetshah/ping-pong-game:latest

