language: java

jdk:
  - oraclejdk13

os: osx

before_install:
  - chmod +x gradlew

script: ./gradlew build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: travis_integration

