language: java

jdk:
  - oraclejdk13

services:
  - docker

os: osx

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

before_deploy:
  - project_version = $(./gradlew currentVersion) echo
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker tag ping-pong-game:${project_version} smeetshah/ping-pong-game:latest

deploy:
  provider: script
  script:
    -docker push smeetshah/ping-pong-game:latest

