version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mytopic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  pingpong:
    build: .
    container_name: pingpong
    ports:
    - "8080:8080"
    expose:
      - "8080"
    links:
      - kafka
    environment:
      KAFKA_CONNECT: kafka:9092